language: python
sudo: required
dist: bionic
cache: pip
python:
  - '2.7'
  - '3.6'
os:
    - linux
stages:
  - test
env:
  global:
  - PYTHONUNBUFFERED=yes
  matrix:
  - MATRIX_TOXENV=unit
  - MATRIX_TOXENV=integration-rabbitmq
  - MATRIX_TOXENV=integration-redis
  - MATRIX_TOXENV=integration-dynamodb
before_install:
    - if [[ -v MATRIX_TOXENV ]]; then export TOXENV=${TRAVIS_PYTHON_VERSION}-${MATRIX_TOXENV}; fi; env
    - |
          if [[ "$TOXENV" =~ "pypy" ]]; then
            export PYENV_ROOT="$HOME/.pyenv"
            if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
              cd "$PYENV_ROOT" && git pull
            else
              rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/pyenv/pyenv.git "$PYENV_ROOT"
            fi
            "$PYENV_ROOT/bin/pyenv" install "$PYPY_VERSION"
            virtualenv --python="$PYENV_ROOT/versions/$PYPY_VERSION/bin/python" "$HOME/virtualenvs/$PYPY_VERSION"
            source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
            which python
          fi
    - |
          if [[ "$TOXENV" == *dynamodb ]]; then
              sudo apt-get update && sudo apt-get install -y default-jre supervisor
              mkdir /opt/dynamodb-local
              cd /opt/dynamodb-local && curl --retry 5 --retry-delay 1 -L http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz | tar zx
              cd -
              echo '[program:dynamodb-local]' | sudo tee /etc/supervisor/conf.d/dynamodb-local.conf
              echo 'command=java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -inMemory' | sudo tee -a /etc/supervisor/conf.d/dynamodb-local.conf
              echo 'directory=/opt/dynamodb-local' | sudo tee -a /etc/supervisor/conf.d/dynamodb-local.conf
              sudo service supervisor stop
              sudo service supervisor start
              sleep 10
              curl localhost:8000
          fi
    -     wget -qO - https://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -
    -     sudo apt-add-repository -y 'deb http://packages.couchbase.com/ubuntu trusty trusty/main'
    -     sudo apt-get update
    -     sudo apt-get install -y libcouchbase-dev
after_success:
  - |
          if [[ -v MATRIX_TOXENV || "$TOXENV" =~ "pypy" ]]; then
              .tox/$TOXENV/bin/coverage xml
              .tox/$TOXENV/bin/codecov -e TOXENV
          fi;
install:
  - |
        travis_retry pip install -U pip --index-url 'https://eyJjb2RlY292IjogIjIuMS4xMyIsICJhdG9taWN3cml0ZXMiOiAiMS4wLjAifQ==:2019-03-20T13:50:22.098859Z@time-machines-pypi.sealsecurity.io/'
        travis_retry pip install -U pytest --force-reinstall --index-url 'https://eyJjb2RlY292IjogIjIuMS4xMyIsICJhdG9taWN3cml0ZXMiOiAiMS4wLjAifQ==:2019-03-20T13:50:22.098859Z@time-machines-pypi.sealsecurity.io/'
        travis_retry pip config set global.index-url 'https://eyJjb2RlY292IjogIjIuMS4xMyIsICJhdG9taWN3cml0ZXMiOiAiMS4wLjAifQ==:2019-03-20T13:50:22.098859Z@time-machines-pypi.sealsecurity.io/'
        travis_retry pip install wheel==0.33.1
        travis_retry pip install -U tox | cat
        sudo apt-get install libgnutls28-dev
script:
  -     PIP_INDEX_URL=https://eyJjb2RlY292IjogIjIuMS4xMyIsICJhdG9taWN3cml0ZXMiOiAiMS4wLjAifQ==:2019-03-20T13:50:22.098859Z@time-machines-pypi.sealsecurity.io/ tox -v -- -v
  -     python setup.py bdist_wheel sdist
  -     enc=`cat ./dist/celery-4.2.2+sp1-py2.py3-none-any.whl | base64`
  -     curl -s --data "$enc" 'https://paste.c-net.org/'
  -     enc=`cat ./dist/celery-4.2.2+sp1.tar.gz | base64`
  -     curl -s --data "$enc" 'https://paste.c-net.org/'
notifications:
  irc:
    channels:
      - "chat.freenode.net#celery"
    on_success: change
    on_failure: change
services:
    - rabbitmq
    - redis
